### ISSUE TITLE
Undefined variable: ip

### ISSUE THREAD

**Issue by kek91** [Perlkonig/grav-plugin-iplocate#1]
`Undefined variable: $ip`
Error occurs in `/­user/­plugins/­iplocate/­iplocate.php` at line 47.

Notice exception occurs because the function `is_null()` just checks if the given variable is null. You may want to switch to `isset()` because this will check that the variable exists AND that it's not null.

**Comment by Perlkonig** [comment]
Thanks for this! I'm not a PHP native, and this just never came up in testing somehow.
