### ISSUE TITLE
How to access the collected IP

### ISSUE THREAD

**Issue by rissson** [Perlkonig/grav-plugin-iplocate#5]
Hey !
I think you forgot to mention how to access the collected IPs !
Maybe store them in a file in /user/data ;)

**Comment by Perlkonig** [comment]
It doesn't store anything, beyond a basic cache. It leverages Grav's built-in caching mechanism to avoid duplicating calls. This isn't an access log or analytics plugin. It's just a way of geolocating your visitor.
